name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository code
    - name: Check out repository
      uses: actions/checkout@v2

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Use the Python version you used in development

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest

    # Run flake8 for linting
    - name: Lint with flake8
      run: |
        flake8 .  # Runs flake8 on all files in the project

    # Run pytest for testing
    - name: Test with pytest
      run: |
        pytest
